#### JDBC
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: root
    password: 494408
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 3
      max-active: 15
      initial-size: 5
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
mybatis:
  mapper-locations: classpath:/mapper/*/*/*.Mapper.xml
  type-aliases-package: cn.ekgc.witmed.*